### PR TITLE
Use math functions to reduce the length of the code

### PR DESCRIPTION
**Pull request by Athozus**
I just used math.min(), math.max() and math.fmod() to reduce the calculations and length of the code, then reduce the lag (if there is).

### CODE REVIEW

**Review by APercy — CHANGES_REQUESTED** [review]
We have 2,5 problems:
1 - ModError: Failed to load and run script from /home/wolfen/.minetest/mods/pa28/init.lua:
/home/wolfen/.minetest/mods/pa28/control.lua:203: ')' expected (to close '(' at line 198) near 'self'

2 - the fuel change broke the flight consumption, because that routine is only used when the plane is iddle, to have a minimal consumption when the engine is started, not zero

2.5: back to the first solution, when I use mouse to turn to right, it turns left when the angle is above the 90 (relative to plane nose). So I'll try something else: the code I used in the motorcycle, lets try it!

**Comment by APercy** [comment]
better, lets put this on airutils and you can improve there

function automobiles_lib.set_yaw_by_mouse(self, dir, steering_limit)
    local rotation = self.object:get_rotation()
    local rot_y = math.deg(rotation.y)
    
    local total = math.abs(math.floor(rot_y/360))

    if rot_y < 0 then rot_y = rot_y + (360*total) end
    if rot_y > 360 then rot_y = rot_y - (360*total) end
    if rot_y >= 270 and dir <= 90 then dir = dir + 360 end
    if rot_y <= 90 and dir >= 270 then dir = dir - 360 end

    local intensity = 2
    if self._intensity then intensity = self._intensity end
    local command = (rot_y - dir) * intensity
    if command < -90 then command = -90 
    elseif command > 90 then command = 90 end
    --minetest.chat_send_all("rotation y: "..rot_y.." - dir: "..dir.." - command: "..(rot_y - dir))

    --minetest.chat_send_all("rotation y: "..rot_y.." - dir: "..dir.." - command: "..command)

	return (-command * steering_limit)/90
end

**Comment by APercy** [comment]
I figured that the problem occurs even on old code, so we need to improve all!

**Comment by APercy** [comment]
I'll wait you fix your code, so then we can improve later then put it on airutils instead the plane code. So all planes will be able to use it

**Comment by Athozus** [comment]
I corrected ) issue.
About fuel consomption, math.max(consumed_fuel, 0.000001) return at least 0.000001, that you want to do if I correctly understood.

**Pull request merged**
